#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CacheService
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
    using Apache.Ignite.Core.Cache.Configuration;
    using Apache.Ignite.Core.Binary;

    [global::System.Data.Linq.Mapping.DatabaseAttribute(Name="test")]
	public partial class CustomerAccountsDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCustomerAccount(CustomerAccount instance);
    partial void UpdateCustomerAccount(CustomerAccount instance);
    partial void DeleteCustomerAccount(CustomerAccount instance);
    #endregion
		
		public CustomerAccountsDataContext() : 
				base(global::CacheService.Properties.Settings.Default.testConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public CustomerAccountsDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CustomerAccountsDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CustomerAccountsDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CustomerAccountsDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CustomerAccount> CustomerAccounts
		{
			get
			{
				return this.GetTable<CustomerAccount>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CustomerAccounts")]
	public partial class CustomerAccount : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _AccountId;
		
		private string _AccountNumber;
		
		private string _AccountName;
		
		private long _AdvertiserId;
		
		private System.Nullable<long> _AgencyId;
		
		private System.Nullable<long> _SalesHouseCustomerId;
		
		private long _PreferredUserId;
		
		private string _CustomerName;
		
		private System.Nullable<byte> _CustomerTypeId;
		
		private string _CustomerNumber;
		
		private string _AgencyName;
		
		private string _PaymentOption;
		
		private System.Nullable<byte> _PaymentOptionId;
		
		private System.Nullable<byte> _PaymentInstrumentTypeId;
		
		private System.Nullable<byte> _SecondaryPaymentInstrumentTypeId;
		
		private string _PaymentInstrumentTypeName;
		
		private string _SecondaryPaymentInstrumentTypeName;
		
		private System.Nullable<System.DateTime> _CreatedDate;
		
		private System.Nullable<int> _PreferredBillToPaymentInstrumentId;
		
		private System.Nullable<int> _SecondaryBillToPaymentInstrumentId;
		
		private System.Nullable<int> _BillToCustomerId;
		
		private string _BillToCustomerName;
		
		private System.Nullable<short> _CurrencyId;
		
		private string _SAPID;
		
		private System.Nullable<byte> _AccountTimeZoneId;
		
		private string _CurrencyType;
		
		private System.Nullable<System.DateTime> _AccountModifiedDateTime;
		
		private System.Nullable<System.DateTime> _CustomerModifiedDateTime;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAccountIdChanging(long value);
    partial void OnAccountIdChanged();
    partial void OnAccountNumberChanging(string value);
    partial void OnAccountNumberChanged();
    partial void OnAccountNameChanging(string value);
    partial void OnAccountNameChanged();
    partial void OnAdvertiserIdChanging(long value);
    partial void OnAdvertiserIdChanged();
    partial void OnAgencyIdChanging(System.Nullable<long> value);
    partial void OnAgencyIdChanged();
    partial void OnSalesHouseCustomerIdChanging(System.Nullable<long> value);
    partial void OnSalesHouseCustomerIdChanged();
    partial void OnPreferredUserIdChanging(long value);
    partial void OnPreferredUserIdChanged();
    partial void OnCustomerNameChanging(string value);
    partial void OnCustomerNameChanged();
    partial void OnCustomerTypeIdChanging(System.Nullable<byte> value);
    partial void OnCustomerTypeIdChanged();
    partial void OnCustomerNumberChanging(string value);
    partial void OnCustomerNumberChanged();
    partial void OnAgencyNameChanging(string value);
    partial void OnAgencyNameChanged();
    partial void OnPaymentOptionChanging(string value);
    partial void OnPaymentOptionChanged();
    partial void OnPaymentOptionIdChanging(System.Nullable<byte> value);
    partial void OnPaymentOptionIdChanged();
    partial void OnPaymentInstrumentTypeIdChanging(System.Nullable<byte> value);
    partial void OnPaymentInstrumentTypeIdChanged();
    partial void OnSecondaryPaymentInstrumentTypeIdChanging(System.Nullable<byte> value);
    partial void OnSecondaryPaymentInstrumentTypeIdChanged();
    partial void OnPaymentInstrumentTypeNameChanging(string value);
    partial void OnPaymentInstrumentTypeNameChanged();
    partial void OnSecondaryPaymentInstrumentTypeNameChanging(string value);
    partial void OnSecondaryPaymentInstrumentTypeNameChanged();
    partial void OnCreatedDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedDateChanged();
    partial void OnPreferredBillToPaymentInstrumentIdChanging(System.Nullable<int> value);
    partial void OnPreferredBillToPaymentInstrumentIdChanged();
    partial void OnSecondaryBillToPaymentInstrumentIdChanging(System.Nullable<int> value);
    partial void OnSecondaryBillToPaymentInstrumentIdChanged();
    partial void OnBillToCustomerIdChanging(System.Nullable<int> value);
    partial void OnBillToCustomerIdChanged();
    partial void OnBillToCustomerNameChanging(string value);
    partial void OnBillToCustomerNameChanged();
    partial void OnCurrencyIdChanging(System.Nullable<short> value);
    partial void OnCurrencyIdChanged();
    partial void OnSAPIDChanging(string value);
    partial void OnSAPIDChanged();
    partial void OnAccountTimeZoneIdChanging(System.Nullable<byte> value);
    partial void OnAccountTimeZoneIdChanged();
    partial void OnCurrencyTypeChanging(string value);
    partial void OnCurrencyTypeChanged();
    partial void OnAccountModifiedDateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnAccountModifiedDateTimeChanged();
    partial void OnCustomerModifiedDateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnCustomerModifiedDateTimeChanged();
    #endregion
		
		public CustomerAccount()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountId", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long AccountId
		{
			get
			{
				return this._AccountId;
			}
			set
			{
				if ((this._AccountId != value))
				{
					this.OnAccountIdChanging(value);
					this.SendPropertyChanging();
					this._AccountId = value;
					this.SendPropertyChanged("AccountId");
					this.OnAccountIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountNumber", DbType="Char(8) NOT NULL", CanBeNull=false)]
		public string AccountNumber
		{
			get
			{
				return this._AccountNumber;
			}
			set
			{
				if ((this._AccountNumber != value))
				{
					this.OnAccountNumberChanging(value);
					this.SendPropertyChanging();
					this._AccountNumber = value;
					this.SendPropertyChanged("AccountNumber");
					this.OnAccountNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountName", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string AccountName
		{
			get
			{
				return this._AccountName;
			}
			set
			{
				if ((this._AccountName != value))
				{
					this.OnAccountNameChanging(value);
					this.SendPropertyChanging();
					this._AccountName = value;
					this.SendPropertyChanged("AccountName");
					this.OnAccountNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdvertiserId", DbType="BigInt NOT NULL")]
		public long AdvertiserId
		{
			get
			{
				return this._AdvertiserId;
			}
			set
			{
				if ((this._AdvertiserId != value))
				{
					this.OnAdvertiserIdChanging(value);
					this.SendPropertyChanging();
					this._AdvertiserId = value;
					this.SendPropertyChanged("AdvertiserId");
					this.OnAdvertiserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AgencyId", DbType="BigInt")]
		public System.Nullable<long> AgencyId
		{
			get
			{
				return this._AgencyId;
			}
			set
			{
				if ((this._AgencyId != value))
				{
					this.OnAgencyIdChanging(value);
					this.SendPropertyChanging();
					this._AgencyId = value;
					this.SendPropertyChanged("AgencyId");
					this.OnAgencyIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SalesHouseCustomerId", DbType="BigInt")]
		public System.Nullable<long> SalesHouseCustomerId
		{
			get
			{
				return this._SalesHouseCustomerId;
			}
			set
			{
				if ((this._SalesHouseCustomerId != value))
				{
					this.OnSalesHouseCustomerIdChanging(value);
					this.SendPropertyChanging();
					this._SalesHouseCustomerId = value;
					this.SendPropertyChanged("SalesHouseCustomerId");
					this.OnSalesHouseCustomerIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PreferredUserId", DbType="BigInt NOT NULL")]
		public long PreferredUserId
		{
			get
			{
				return this._PreferredUserId;
			}
			set
			{
				if ((this._PreferredUserId != value))
				{
					this.OnPreferredUserIdChanging(value);
					this.SendPropertyChanging();
					this._PreferredUserId = value;
					this.SendPropertyChanged("PreferredUserId");
					this.OnPreferredUserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerName", DbType="NVarChar(100)")]
		public string CustomerName
		{
			get
			{
				return this._CustomerName;
			}
			set
			{
				if ((this._CustomerName != value))
				{
					this.OnCustomerNameChanging(value);
					this.SendPropertyChanging();
					this._CustomerName = value;
					this.SendPropertyChanged("CustomerName");
					this.OnCustomerNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerTypeId", DbType="TinyInt")]
		public System.Nullable<byte> CustomerTypeId
		{
			get
			{
				return this._CustomerTypeId;
			}
			set
			{
				if ((this._CustomerTypeId != value))
				{
					this.OnCustomerTypeIdChanging(value);
					this.SendPropertyChanging();
					this._CustomerTypeId = value;
					this.SendPropertyChanged("CustomerTypeId");
					this.OnCustomerTypeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerNumber", DbType="Char(10)")]
		public string CustomerNumber
		{
			get
			{
				return this._CustomerNumber;
			}
			set
			{
				if ((this._CustomerNumber != value))
				{
					this.OnCustomerNumberChanging(value);
					this.SendPropertyChanging();
					this._CustomerNumber = value;
					this.SendPropertyChanged("CustomerNumber");
					this.OnCustomerNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AgencyName", DbType="NVarChar(100)")]
		public string AgencyName
		{
			get
			{
				return this._AgencyName;
			}
			set
			{
				if ((this._AgencyName != value))
				{
					this.OnAgencyNameChanging(value);
					this.SendPropertyChanging();
					this._AgencyName = value;
					this.SendPropertyChanged("AgencyName");
					this.OnAgencyNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaymentOption", DbType="NVarChar(100)")]
		public string PaymentOption
		{
			get
			{
				return this._PaymentOption;
			}
			set
			{
				if ((this._PaymentOption != value))
				{
					this.OnPaymentOptionChanging(value);
					this.SendPropertyChanging();
					this._PaymentOption = value;
					this.SendPropertyChanged("PaymentOption");
					this.OnPaymentOptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaymentOptionId", DbType="TinyInt")]
		public System.Nullable<byte> PaymentOptionId
		{
			get
			{
				return this._PaymentOptionId;
			}
			set
			{
				if ((this._PaymentOptionId != value))
				{
					this.OnPaymentOptionIdChanging(value);
					this.SendPropertyChanging();
					this._PaymentOptionId = value;
					this.SendPropertyChanged("PaymentOptionId");
					this.OnPaymentOptionIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaymentInstrumentTypeId", DbType="TinyInt")]
		public System.Nullable<byte> PaymentInstrumentTypeId
		{
			get
			{
				return this._PaymentInstrumentTypeId;
			}
			set
			{
				if ((this._PaymentInstrumentTypeId != value))
				{
					this.OnPaymentInstrumentTypeIdChanging(value);
					this.SendPropertyChanging();
					this._PaymentInstrumentTypeId = value;
					this.SendPropertyChanged("PaymentInstrumentTypeId");
					this.OnPaymentInstrumentTypeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SecondaryPaymentInstrumentTypeId", DbType="TinyInt")]
		public System.Nullable<byte> SecondaryPaymentInstrumentTypeId
		{
			get
			{
				return this._SecondaryPaymentInstrumentTypeId;
			}
			set
			{
				if ((this._SecondaryPaymentInstrumentTypeId != value))
				{
					this.OnSecondaryPaymentInstrumentTypeIdChanging(value);
					this.SendPropertyChanging();
					this._SecondaryPaymentInstrumentTypeId = value;
					this.SendPropertyChanged("SecondaryPaymentInstrumentTypeId");
					this.OnSecondaryPaymentInstrumentTypeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaymentInstrumentTypeName", DbType="NVarChar(50)")]
		public string PaymentInstrumentTypeName
		{
			get
			{
				return this._PaymentInstrumentTypeName;
			}
			set
			{
				if ((this._PaymentInstrumentTypeName != value))
				{
					this.OnPaymentInstrumentTypeNameChanging(value);
					this.SendPropertyChanging();
					this._PaymentInstrumentTypeName = value;
					this.SendPropertyChanged("PaymentInstrumentTypeName");
					this.OnPaymentInstrumentTypeNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SecondaryPaymentInstrumentTypeName", DbType="NVarChar(50)")]
		public string SecondaryPaymentInstrumentTypeName
		{
			get
			{
				return this._SecondaryPaymentInstrumentTypeName;
			}
			set
			{
				if ((this._SecondaryPaymentInstrumentTypeName != value))
				{
					this.OnSecondaryPaymentInstrumentTypeNameChanging(value);
					this.SendPropertyChanging();
					this._SecondaryPaymentInstrumentTypeName = value;
					this.SendPropertyChanged("SecondaryPaymentInstrumentTypeName");
					this.OnSecondaryPaymentInstrumentTypeNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreatedDate
		{
			get
			{
				return this._CreatedDate;
			}
			set
			{
				if ((this._CreatedDate != value))
				{
					this.OnCreatedDateChanging(value);
					this.SendPropertyChanging();
					this._CreatedDate = value;
					this.SendPropertyChanged("CreatedDate");
					this.OnCreatedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PreferredBillToPaymentInstrumentId", DbType="Int")]
		public System.Nullable<int> PreferredBillToPaymentInstrumentId
		{
			get
			{
				return this._PreferredBillToPaymentInstrumentId;
			}
			set
			{
				if ((this._PreferredBillToPaymentInstrumentId != value))
				{
					this.OnPreferredBillToPaymentInstrumentIdChanging(value);
					this.SendPropertyChanging();
					this._PreferredBillToPaymentInstrumentId = value;
					this.SendPropertyChanged("PreferredBillToPaymentInstrumentId");
					this.OnPreferredBillToPaymentInstrumentIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SecondaryBillToPaymentInstrumentId", DbType="Int")]
		public System.Nullable<int> SecondaryBillToPaymentInstrumentId
		{
			get
			{
				return this._SecondaryBillToPaymentInstrumentId;
			}
			set
			{
				if ((this._SecondaryBillToPaymentInstrumentId != value))
				{
					this.OnSecondaryBillToPaymentInstrumentIdChanging(value);
					this.SendPropertyChanging();
					this._SecondaryBillToPaymentInstrumentId = value;
					this.SendPropertyChanged("SecondaryBillToPaymentInstrumentId");
					this.OnSecondaryBillToPaymentInstrumentIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BillToCustomerId", DbType="Int")]
		public System.Nullable<int> BillToCustomerId
		{
			get
			{
				return this._BillToCustomerId;
			}
			set
			{
				if ((this._BillToCustomerId != value))
				{
					this.OnBillToCustomerIdChanging(value);
					this.SendPropertyChanging();
					this._BillToCustomerId = value;
					this.SendPropertyChanged("BillToCustomerId");
					this.OnBillToCustomerIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BillToCustomerName", DbType="NVarChar(100)")]
		public string BillToCustomerName
		{
			get
			{
				return this._BillToCustomerName;
			}
			set
			{
				if ((this._BillToCustomerName != value))
				{
					this.OnBillToCustomerNameChanging(value);
					this.SendPropertyChanging();
					this._BillToCustomerName = value;
					this.SendPropertyChanged("BillToCustomerName");
					this.OnBillToCustomerNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurrencyId", DbType="SmallInt")]
		public System.Nullable<short> CurrencyId
		{
			get
			{
				return this._CurrencyId;
			}
			set
			{
				if ((this._CurrencyId != value))
				{
					this.OnCurrencyIdChanging(value);
					this.SendPropertyChanging();
					this._CurrencyId = value;
					this.SendPropertyChanged("CurrencyId");
					this.OnCurrencyIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SAPID", DbType="NVarChar(10)")]
		public string SAPID
		{
			get
			{
				return this._SAPID;
			}
			set
			{
				if ((this._SAPID != value))
				{
					this.OnSAPIDChanging(value);
					this.SendPropertyChanging();
					this._SAPID = value;
					this.SendPropertyChanged("SAPID");
					this.OnSAPIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountTimeZoneId", DbType="TinyInt")]
		public System.Nullable<byte> AccountTimeZoneId
		{
			get
			{
				return this._AccountTimeZoneId;
			}
			set
			{
				if ((this._AccountTimeZoneId != value))
				{
					this.OnAccountTimeZoneIdChanging(value);
					this.SendPropertyChanging();
					this._AccountTimeZoneId = value;
					this.SendPropertyChanged("AccountTimeZoneId");
					this.OnAccountTimeZoneIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurrencyType", DbType="NVarChar(35)")]
		public string CurrencyType
		{
			get
			{
				return this._CurrencyType;
			}
			set
			{
				if ((this._CurrencyType != value))
				{
					this.OnCurrencyTypeChanging(value);
					this.SendPropertyChanging();
					this._CurrencyType = value;
					this.SendPropertyChanged("CurrencyType");
					this.OnCurrencyTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountModifiedDateTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> AccountModifiedDateTime
		{
			get
			{
				return this._AccountModifiedDateTime;
			}
			set
			{
				if ((this._AccountModifiedDateTime != value))
				{
					this.OnAccountModifiedDateTimeChanging(value);
					this.SendPropertyChanging();
					this._AccountModifiedDateTime = value;
					this.SendPropertyChanged("AccountModifiedDateTime");
					this.OnAccountModifiedDateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerModifiedDateTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> CustomerModifiedDateTime
		{
			get
			{
				return this._CustomerModifiedDateTime;
			}
			set
			{
				if ((this._CustomerModifiedDateTime != value))
				{
					this.OnCustomerModifiedDateTimeChanging(value);
					this.SendPropertyChanging();
					this._CustomerModifiedDateTime = value;
					this.SendPropertyChanged("CustomerModifiedDateTime");
					this.OnCustomerModifiedDateTimeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}

    [Serializable]
    public class CustomerAccount_ignite //: IBinarizable
    {

        public CustomerAccount_ignite (CustomerAccount account)
        {
            this.AccountId = account.AccountId;
            this.AccountModifiedDateTime = account.AccountModifiedDateTime.Value.ToUniversalTime();
            this.AccountName = account.AccountName;
            this.AccountNumber = account.AccountNumber;
            this.AccountTimeZoneId = account.AccountTimeZoneId;
            this.AdvertiserId = account.AdvertiserId;
            this.AgencyId = account.AgencyId;
            this.AgencyName = account.AgencyName;
            this.BillToCustomerId = account.BillToCustomerId;
            this.BillToCustomerName = account.BillToCustomerName;
            this.CreatedDate = account.CreatedDate.Value.ToUniversalTime();
            this.CurrencyId = account.CurrencyId;
            this.CurrencyType = account.CurrencyType;
            this.CustomerModifiedDateTime = account.CustomerModifiedDateTime.Value.ToUniversalTime();
            this.CustomerName = account.CustomerName;
            this.CustomerNumber = account.CustomerNumber;
            this.CustomerTypeId = account.CustomerTypeId;
            this.PaymentInstrumentTypeId = account.PaymentInstrumentTypeId;
            this.PaymentInstrumentTypeName = account.PaymentInstrumentTypeName;
            this.PaymentOption = account.PaymentOption;
            this.PaymentOptionId = account.PaymentOptionId;
            this.PreferredBillToPaymentInstrumentId = account.PreferredBillToPaymentInstrumentId;
            this.PreferredUserId = account.PreferredUserId;
            this.SalesHouseCustomerId = account.SalesHouseCustomerId;
            this.SAPID = account.SAPID;
            this.SecondaryBillToPaymentInstrumentId = account.SecondaryBillToPaymentInstrumentId;
            this.SecondaryPaymentInstrumentTypeId = account.SecondaryPaymentInstrumentTypeId;
            this.SecondaryPaymentInstrumentTypeName = SecondaryPaymentInstrumentTypeName;

        }

        /*
        public void WriteBinary(IBinaryWriter writer)
        {
            // Alphabetic field order is required for SQL DML to work.
            // Even if DML is not used, alphabetic order is recommended.
            writer.WriteLong("AccountId", AccountId);
            writer.WriteString("AccountNumber", AccountNumber);
            writer.WriteString("AccountName", AccountName);
            writer.WriteLong("AdvertiserId", AdvertiserId);
        }

        public void ReadBinary(IBinaryReader reader)
        {
            // Read order does not matter, however, reading in the same order 
            // as writing improves performance.
            AccountId=reader.ReadLong("AccountId");
            AccountNumber=reader.ReadString("AccountNumber");
            AccountName=reader.ReadString("AccountName");
            AdvertiserId=reader.ReadLong("AdvertiserId");
        }*/

        [QuerySqlField(IsIndexed = true)]
        public long _AccountId;

        [QuerySqlField]
        public string _AccountNumber;

        [QuerySqlField]
        public string _AccountName;

        [QuerySqlField]
        public long _AdvertiserId;

        [QuerySqlField]
        public System.Nullable<long> _AgencyId;

        [QuerySqlField]
        public System.Nullable<long> _SalesHouseCustomerId;

        [QuerySqlField]
        public long _PreferredUserId;

        [QuerySqlField]
        public string _CustomerName;

        [QuerySqlField]
        public System.Nullable<byte> _CustomerTypeId;

        [QuerySqlField]
        public string _CustomerNumber;

        [QuerySqlField]
        public string _AgencyName;

        [QuerySqlField]
        public string _PaymentOption;

        [QuerySqlField]
        public System.Nullable<byte> _PaymentOptionId;

        [QuerySqlField]
        public System.Nullable<byte> _PaymentInstrumentTypeId;

        [QuerySqlField]
        public System.Nullable<byte> _SecondaryPaymentInstrumentTypeId;

        [QuerySqlField]
        public string _PaymentInstrumentTypeName;

        [QuerySqlField]
        public string _SecondaryPaymentInstrumentTypeName;

        [QuerySqlField]
        public System.Nullable<System.DateTime> _CreatedDate;

        [QuerySqlField]
        public System.Nullable<int> _PreferredBillToPaymentInstrumentId;

        [QuerySqlField]
        public System.Nullable<int> _SecondaryBillToPaymentInstrumentId;

        [QuerySqlField]
        public System.Nullable<int> _BillToCustomerId;

        [QuerySqlField]
        public string _BillToCustomerName;

        [QuerySqlField]
        public System.Nullable<short> _CurrencyId;

        [QuerySqlField]
        public string _SAPID;

        [QuerySqlField]
        public System.Nullable<byte> _AccountTimeZoneId;

        [QuerySqlField]
        public string _CurrencyType;

        [QuerySqlField]
        public System.Nullable<System.DateTime> _AccountModifiedDateTime;

        [QuerySqlField]
        public System.Nullable<System.DateTime> _CustomerModifiedDateTime;

        
        public long AccountId
        {
            get
            {
                return this._AccountId;
            }
            set
            {
                this._AccountId = value;
            }
        }

        public string AccountNumber
        {
            get
            {
                return this._AccountNumber;
            }
            set
            {
                    this._AccountNumber = value;
            }
        }

        public string AccountName
        {
            get
            {
                return this._AccountName;
            }
            set
            {
                    this._AccountName = value;
            }
        }

        public long AdvertiserId
        {
            get
            {
                return this._AdvertiserId;
            }
            set
            {
                    this._AdvertiserId = value;
            }
        }

        public System.Nullable<long> AgencyId
        {
            get
            {
                return this._AgencyId;
            }
            set
            {
                    this._AgencyId = value;
            }
        }

        public System.Nullable<long> SalesHouseCustomerId
        {
            get
            {
                return this._SalesHouseCustomerId;
            }
            set
            {

                    this._SalesHouseCustomerId = value;
            }
        }

        public long PreferredUserId
        {
            get
            {
                return this._PreferredUserId;
            }
            set
            {
                    this._PreferredUserId = value;
            }
        }

        public string CustomerName
        {
            get
            {
                return this._CustomerName;
            }
            set
            {
                    this._CustomerName = value;
            }
        }

        public System.Nullable<byte> CustomerTypeId
        {
            get
            {
                return this._CustomerTypeId;
            }
            set
            {
                    this._CustomerTypeId = value;
            }
        }

        public string CustomerNumber
        {
            get
            {
                return this._CustomerNumber;
            }
            set
            {
                    this._CustomerNumber = value;
            }
        }

        public string AgencyName
        {
            get
            {
                return this._AgencyName;
            }
            set
            {
                    this._AgencyName = value;
            }
        }

        public string PaymentOption
        {
            get
            {
                return this._PaymentOption;
            }
            set
            {
                    this._PaymentOption = value;
            }
        }

        public System.Nullable<byte> PaymentOptionId
        {
            get
            {
                return this._PaymentOptionId;
            }
            set
            {
                    this._PaymentOptionId = value;
            }
        }

        public System.Nullable<byte> PaymentInstrumentTypeId
        {
            get
            {
                return this._PaymentInstrumentTypeId;
            }
            set
            {
                    this._PaymentInstrumentTypeId = value;
            }
        }

        public System.Nullable<byte> SecondaryPaymentInstrumentTypeId
        {
            get
            {
                return this._SecondaryPaymentInstrumentTypeId;
            }
            set
            {
                    this._SecondaryPaymentInstrumentTypeId = value;
            }
        }

        public string PaymentInstrumentTypeName
        {
            get
            {
                return this._PaymentInstrumentTypeName;
            }
            set
            {
                    this._PaymentInstrumentTypeName = value;
            }
        }

        public string SecondaryPaymentInstrumentTypeName
        {
            get
            {
                return this._SecondaryPaymentInstrumentTypeName;
            }
            set
            {
                    this._SecondaryPaymentInstrumentTypeName = value;
            }
        }

        public System.Nullable<System.DateTime> CreatedDate
        {
            get
            {
                return this._CreatedDate;
            }
            set
            {
                    this._CreatedDate = value;
            }
        }

        public System.Nullable<int> PreferredBillToPaymentInstrumentId
        {
            get
            {
                return this._PreferredBillToPaymentInstrumentId;
            }
            set
            {
                    this._PreferredBillToPaymentInstrumentId = value;
            }
        }

        public System.Nullable<int> SecondaryBillToPaymentInstrumentId
        {
            get
            {
                return this._SecondaryBillToPaymentInstrumentId;
            }
            set
            {
                    this._SecondaryBillToPaymentInstrumentId = value;
            }
        }

        public System.Nullable<int> BillToCustomerId
        {
            get
            {
                return this._BillToCustomerId;
            }
            set
            {
                    this._BillToCustomerId = value;
            }
        }

        public string BillToCustomerName
        {
            get
            {
                return this._BillToCustomerName;
            }
            set
            {
                    this._BillToCustomerName = value;
            }
        }

        public System.Nullable<short> CurrencyId
        {
            get
            {
                return this._CurrencyId;
            }
            set
            {

                    this._CurrencyId = value;
            }
        }

        public string SAPID
        {
            get
            {
                return this._SAPID;
            }
            set
            {
                    this._SAPID = value;
            }
        }

        public System.Nullable<byte> AccountTimeZoneId
        {
            get
            {
                return this._AccountTimeZoneId;
            }
            set
            {
                    this._AccountTimeZoneId = value;
            }
        }

        public string CurrencyType
        {
            get
            {
                return this._CurrencyType;
            }
            set
            {
                    this._CurrencyType = value;
            }
        }


        public System.Nullable<System.DateTime> AccountModifiedDateTime
        {
            get
            {
                return this._AccountModifiedDateTime;
            }
            set
            {
                    this._AccountModifiedDateTime = value;
            }
        }

        public System.Nullable<System.DateTime> CustomerModifiedDateTime
        {
            get
            {
                return this._CustomerModifiedDateTime;
            }
            set
            {
                    this._CustomerModifiedDateTime = value;
            }
        }

    }

}
#pragma warning restore 1591
